### ISSUE TITLE
Create color syntax for `.zndsl` files (`.features` should be deprecated)

### ISSUE THREAD

**Issue by wirednkod** [paritytech/zombienet-vscode-extension#7]

**Comment by chevdor** [comment]
I would recommend to settle down asap on the file extension we decide using and deprecating the old one.

I went away fronm `.features` as I think this is not specific enough (we will have collisions with other files such as [this](https://fileinfo.com/extension/feature)). The chances to have colisions with `.zndsl` are very low. @wirednkod mentioned also `.zn` as option but I fear we will step on some compression (`z`) related formats.

`.znet` would work as well.

**Comment by wirednkod** [comment]
@chevdor I would suggest to go with `.zndsl` as you already proposed it. What do you think @pepoviola ?

**Comment by chevdor** [comment]
`.zndsl` is indeed, the simplest/shortest I could come up with while staying away from collisions.
That also leaves room for other `.zn<xyz>` if we ever need other files for ZombieNet.

**Comment by pepoviola** [comment]
`.zndsl` sounds good :)
Thanks!!

**Comment by wirednkod** [comment]
> `.zndsl` sounds good :) Thanks!!

#8 and Zombienet's [#427](https://github.com/paritytech/zombienet/pull/427) should finalize the deprecation

**Comment by wirednkod** [comment]
Following a discussion with @chevdor it was clarified to me that `.zndsl` should actually have a `yaml` format.
As a result we need to create a json schema that will add to the extension the auto-detection of `yaml`-like format for this type of files
